[toolchain]
channel = "nightly-2024-04-24"
components = ["rust-src", "rustc-dev", "llvm-tools"]
# commit_hash = 244da22fabd9fa677bbd0ac601a88e5ca6917526

#commit_hash = "1a5f8bce74ee432f7cc3aa131bc3d6920e06de10"
# Whenever changing the nightly channel, update the commit hash above, and make
# sure to change `REQUIRED_TOOLCHAIN` in `crates/rustc_codegen_spirv/build.rs` also.
